# Generated by Django 3.2 on 2025-02-23 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_remove_title_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='rating',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Рейтинг'),
        ),
    ]
